# Generated by Django 5.2.4 on 2025-07-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learning_outcomes',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=49, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='students_enrolled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='target_audience',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='total_hours',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='course',
            name='total_lessons',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='course',
            name='total_weeks',
            field=models.IntegerField(default=4),
        ),
    ]
